### ISSUE TITLE
ImageMagick.MagickCoderErrorException: bad adaptive filter value

### ISSUE THREAD

**Issue by buffyuwu** [tgstation/MapDiffBot#135]
hope i'm supposed to report this here and also hope that it hasnt already been reported
seeing this error more frequently than i'd like

https://github.com/FortunaSS13/Fortuna/runs/4132561566
```
ImageMagick.MagickCoderErrorException: bad adaptive filter value `' @ error/png.c/MagickPNGErrorHandler/1714
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadBlob(MagickSettings settings, Byte[] data, Int32 length)
   at ImageMagick.MagickImage.Read(Byte[] data, Int32 length, MagickReadSettings readSettings, Boolean ping)
   at MapDiffBot.Core.PayloadProcessor.<GenerateDiffs>g__GenerateDifferenceImage|14_19(Image before, Image after, <>c__DisplayClass14_5& )
   at MapDiffBot.Core.PayloadProcessor.<>c__DisplayClass14_1.<<GenerateDiffs>g__GetResult|4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MapDiffBot.Core.PayloadProcessor.GenerateDiffs(PullRequest pullRequest, Int64 checkRunId, IReadOnlyList`1 changedDmms, IServiceScope scope, CancellationToken cancellationToken)
   at MapDiffBot.Core.PayloadProcessor.ScanPullRequestImpl(Int64 repositoryId, Int32 pullRequestNumber, IServiceScope scope, CancellationToken cancellationToken)

```

**Comment by AffectedArc07** [comment]
Try re-running the check for me?

**Comment by buffyuwu** [comment]
> Try re-running the check for me?

yeah rerunning it twice fixed it but i have anxiety about rerunning jobs multiple times after cit got banned from travis lol

**Comment by AffectedArc07** [comment]
Dont be afraid of rerunning MDB. It wont autoban you, and I tend to inform before manually informing.

**Comment by AffectedArc07** [comment]
Closing since this is seemingly a fluke
