### ISSUE TITLE
not found again (share mounting issues?)

### ISSUE THREAD

**Issue by optimumtact** [tgstation/MapDiffBot#49]
An error occurred during the operation:
https://github.com/tgstation/tgstation/pull/37595
```
Octokit.NotFoundException: repositories/3234987/pulls/37595/files was not found.
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext() in S:\Documents\Actual Documents\DA Git\octokit.net\Octokit\Clients\ApiPagination.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.GitHubManager.<GetPullRequestChangedFiles>d__11.MoveNext() in /src/MapDiffBot/GitHubManager.cs:line 213
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<ScanPullRequest>d__13.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 164
```

**Comment by Cyberboss** [comment]
Or should I? The fact that it 404'd on the pr files but not posting the comment confuses the hell out of me

**Comment by Cyberboss** [comment]
Gonna write this off as a fluke on githubs end, haven't seen this error in forever
