### ISSUE TITLE
All images return "Error Fetching Resources"

### ISSUE THREAD

**Issue by DamianX** [tgstation/MapDiffBot#85]
All images return "Error Fetching Resources", there are errors in the log.

Link to erroring PR: https://github.com/vgstation-coders/vgstation13/pull/18674/checks

```
Job 1:
Path: maps/packedstation.dmm
Before:
Command Line: 
Output:

Logs:

After:
Command Line: 
Output:

Logs:

Exceptions:
System.AggregateException: One or more errors occurred. (Could not find a part of the path '/app/App_Data/MapDiffs/vgstation-coders/vgstation13/18674/packedstation.dmm.before.png'.) ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/App_Data/MapDiffs/vgstation-coders/vgstation13/18674/packedstation.dmm.before.png'.
   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at MapDiffBot.Core.DefaultIOManager.<>c__DisplayClass13_0.<MoveFile>b__0() in /src/MapDiffBot/DefaultIOManager.cs:line 128
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.Core.Generator.<RenderMap>d__9.MoveNext() in /src/MapDiffBot/Generator.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<>c__DisplayClass14_4.<<GenerateDiffs>g__RenderOldMap|10>d.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 513
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<GenerateDiffs>d__14.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 525
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/App_Data/MapDiffs/vgstation-coders/vgstation13/18674/packedstation.dmm.before.png'.
   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at MapDiffBot.Core.DefaultIOManager.<>c__DisplayClass13_0.<MoveFile>b__0() in /src/MapDiffBot/DefaultIOManager.cs:line 128
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.Core.Generator.<RenderMap>d__9.MoveNext() in /src/MapDiffBot/Generator.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<>c__DisplayClass14_4.<<GenerateDiffs>g__RenderOldMap|10>d.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 513
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<GenerateDiffs>d__14.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 525<---

System.AggregateException: One or more errors occurred. (Could not find a part of the path '/app/App_Data/MapDiffs/vgstation-coders/vgstation13/18674/packedstation.after.png'.) ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/App_Data/MapDiffs/vgstation-coders/vgstation13/18674/packedstation.after.png'.
   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at MapDiffBot.Core.DefaultIOManager.<>c__DisplayClass13_0.<MoveFile>b__0() in /src/MapDiffBot/DefaultIOManager.cs:line 128
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.Core.Generator.<RenderMap>d__9.MoveNext() in /src/MapDiffBot/Generator.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<>c__DisplayClass14_4.<<GenerateDiffs>g__DiffAndRenderNewMap|8>d.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 482
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<GenerateDiffs>d__14.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 495
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/App_Data/MapDiffs/vgstation-coders/vgstation13/18674/packedstation.after.png'.
   at System.IO.UnixFileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at MapDiffBot.Core.DefaultIOManager.<>c__DisplayClass13_0.<MoveFile>b__0() in /src/MapDiffBot/DefaultIOManager.cs:line 128
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.Core.Generator.<RenderMap>d__9.MoveNext() in /src/MapDiffBot/Generator.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<>c__DisplayClass14_4.<<GenerateDiffs>g__DiffAndRenderNewMap|8>d.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 482
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<GenerateDiffs>d__14.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 495<---


```

**Comment by Cyberboss** [comment]
fuck what did I break

**Comment by Cyberboss** [comment]
Rerun the check to see if it's working now please

**Comment by DamianX** [comment]
Still borked, seems to be stuck:

`[16:40:16]: Initializing...
[16:40:16]: Cleaning working directory...
[16:40:17]: Working directory cleaned!
[16:40:17]: Moving HEAD to pull request base...
[16:40:17]: Looking for dme to use in /app/App_Data/Repositories/vgstation-coders/vgstation13/
[16:40:17]: Selected /app/App_Data/Repositories/vgstation-coders/vgstation13/vgstation13.dme out of 1 possibilities
[16:40:24]: Creating old map cache of maps/packedstation.dmm
[16:40:30]: Creating and moving HEAD to pull request merge commit...
[16:40:35]: Getting diff region for maps/packedstation.dmm...
[16:40:54]: Diff region for maps/packedstation.dmm: (169, 171) => (289, 287)
[16:40:54]: Performing after rendering for maps/packedstation.dmm...
[16:42:20]: After rendering for /app/App_Data/MapDiffs/vgstation-coders/vgstation13/18674/packedstation.after.png complete!
[16:42:20]: Moving HEAD back to pull request base...
[16:42:25]: Performing before rendering for maps/packedstation.dmm...
[16:43:20]: Before rendering for maps/packedstation.dmm complete!
[16:43:20]: Renderings complete, finalizing...
[16:43:25]: Cleaning working directory...`

**Comment by Cyberboss** [comment]
Ahh, that's another fuckup #88

**Comment by DamianX** [comment]
STILL happening, but at least the "raw" links work. Same PR.

**Comment by Cyberboss** [comment]
For images that large, that's normal
