### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by Mewchild** [tgstation/MapDiffBot#93]
https://github.com/VOREStation/VOREStation/pull/4073/checks?check_run_id=9046328
```
System.ArgumentException: Value '' is not a valid 'CheckStatus' enum value.
   at Octokit.StringEnum`1.ParseValue() in C:\projects\octokit-net\Octokit\Models\Response\StringEnum.cs:line 146
   at Octokit.StringEnum`1.get_Value() in C:\projects\octokit-net\Octokit\Models\Response\StringEnum.cs:line 45
   at lambda_method(Closure , Object )
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.TrySerializeUnknownTypes(Object input, Object& output) in C:\projects\octokit-net\Octokit\Http\SimpleJsonSerializer.cs:line 75
   at Octokit.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in C:\projects\octokit-net\Octokit\SimpleJson.cs:line 1054
   at Octokit.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder) in C:\projects\octokit-net\Octokit\SimpleJson.cs:line 1082
   at Octokit.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in C:\projects\octokit-net\Octokit\SimpleJson.cs:line 1031
   at Octokit.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder) in C:\projects\octokit-net\Octokit\SimpleJson.cs:line 1061
   at Octokit.SimpleJson.SerializeObject(Object json, IJsonSerializerStrategy jsonSerializerStrategy) in C:\projects\octokit-net\Octokit\SimpleJson.cs:line 620
   at Octokit.Internal.JsonHttpPipeline.SerializeRequest(IRequest request) in C:\projects\octokit-net\Octokit\Http\JsonHttpPipeline.cs:line 39
   at Octokit.Connection.<Run>d__57`1.MoveNext() in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 625
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Patch>d__32`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.GitHubManager.<UpdateCheckRun>d__16.MoveNext() in /src/MapDiffBot/GitHubManager.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.Core.LocalRepositoryManager.<TryLoadRepository>d__6.MoveNext() in /src/MapDiffBot/LocalRepositoryManager.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.LocalRepositoryManager.<GetRepository>d__7.MoveNext() in /src/MapDiffBot/LocalRepositoryManager.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<GenerateDiffs>d__14.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 328
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.Core.PayloadProcessor.<ScanPullRequestImpl>d__13.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 194
```

**Comment by Cyberboss** [comment]
Addressed by #94
