### ISSUE TITLE
System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by DamianX** [tgstation/MapDiffBot#96]
https://github.com/vgstation-coders/vgstation13/commit/8e3fbafa79882a1611f12e8c6a9c3bb864df04d1
https://github.com/vgstation-coders/vgstation13/runs/10241952

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at MapDiffBot.Core.PayloadProcessor.<>c__DisplayClass14_3.<<GenerateDiffs>g__GetDmeToUse|7>d.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 349
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MapDiffBot.Core.PayloadProcessor.<GenerateDiffs>d__14.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 410
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MapDiffBot.Core.PayloadProcessor.<ScanPullRequestImpl>d__13.MoveNext() in /src/MapDiffBot/PayloadProcessor.cs:line 199
```

**Comment by francinum** [comment]
Reproduced with DMCA:
https://github.com/ColonialMarines-Mirror/ColonialMarines-2018/pull/92/checks?check_run_id=12080681

**Comment by Cyberboss** [comment]
https://github.com/tgstation/MapDiffBot/blob/master/MapDiffBot/Core/PayloadProcessor.cs#L349

We're assuming repositories HAVE a .dme. Should instead error out if none exist.
